spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db_planet_api
        username: app
        password: 123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
            dialect: org.hibernate.dialect.PostgreSQLDialect